language: go
go:
- 1.7
git:
  depth: 9999999
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script:
    - echo hi
    - echo bye
  skip_cleanup: true
  on:
    repo: getcarina/carina
    branch: secure-deploy-with-pull-requests
