language: go
go:
- 1.7
git:
  depth: 9999999
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script:
    secure: "H+aalDqPwYNW3FZQUADhDKcggql0S7Q/RCtu6p+l375Og5WX5RSo86Obi/aADkc1HqUXmThXCJI2LvGPEyCB7qvKl+6JzjKSJo7HB2uDTaYMhvAcmCC6HSuqtt5kWfd45EECLJrmApLKYX8xy/F60rmJE81zTKzb8M5UA0S4rqxd+eqg0/u4xabUGbQLMrO3cE6NB0w6395yMFnQoVFQzasEmUwNEiv+KA2+IeGV18oSKOrYZft00/zYYGfbswPHtvPbOoTZdS95JT8fuHtSsN9d6wRAaIJSns7Yb3mwtkJhFcpCMSN0lqnVdzY/Imer6M1kMDPagg3Gw6w6YOWdIxUr794ARikZc+mEoeUFXEUBjoCRLb9MZkU8c3bigPPhoGUoHkmESHwF7RCNekrsG1Bh5/bdOYWQ8nL378KXD7z7ATXjlxXrZQl1GSt90XTMSenVXaPfsCgFVNtqR10w0wppQLgJ8l6K7iVlZslEPMijkrQmaDSuN6pJQ/3wGWuTkDSCXMYWgMi6Lzak7XUOtzAF1qEDAiZZ8tz9oTnT6bCsDx4LYjnxI8cgKFrJJf/FBbXKcVZqinYkF2++a0xJC5tppIvRrMO/E4DFt0yP29VhVfBPQUUxEptqkTrW8iSa66cCn7aiTuXylHTopAp06Lr2zKoWusypUAaAj59rMmI="
  skip_cleanup: true
  on:
    repo: getcarina/carina
    branch: secure-deploy-with-pull-requests
