language: go
go:
- 1.7
git:
  depth: 9999999
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script:
    secure: "18ijEFduzonG+j8mEOzvx2/mIoozJ+nq/eSjRBOj691jzH9cJGyVQu8EDFNJfIc+LSC8abtyfij59Fvhe54erKiiHaTBbZm1wyn+TZq0CNgOg5sS6ctVFg4yLLZxDToWkIjaFzawypS9zQk479LvjHKnHLRrfn1Qp0LDNSb2BOQ9xCJbqTPakTDr3U1Ykd1YusBstn6G9XiMcZjEx/whk1LzVUXgFhRAKKMJn2JltkIKSkaPyeIh6ysTwnbSneGGSXHYJjQ6G0FbaTbU0kcfxhNZdRlXkKzrIDrWj+1dOHZmBoFJaWeiVRP2l7oHhJqVF8+G6xiY9llZkuT93SUA9D80xr4HWGC7imgahnxMlktUy99lygIXfNHn8g16vPck8HW0RxNY70MfYdTdv3i/96hRh8w/KuH3BKvqrNNeYReWAz84Ae4dbepmzBbFoaRpkQvPn2bKgpR8N7Pb4TwqcofXGaTdnRyB+vBxgEM1oyo2cWZRgie86hdgNFu5VRSef+u07FcBuVIMs9vSxHVim651LrQ4R6uRq0DYUIkLQcY4cwL9I/XGjrqBxLQIloycf7iIxocECF6eVlMeYdhYK0Dahf95mk1LAQv8dLVOxX55ss1NuhPZtUZHE/VDmQyIU7yZuF0wmahAZYZNBu8Cn1lbQyHuZKShil9ftvFeCdk="
  skip_cleanup: true
  on:
    repo: getcarina/carina
    tags: true
