language: go
go:
- 1.7
git:
  depth: 9999999
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script:
    secure: "T84mXr/I618Un5djQS9oSMo+2E9i/lUstxrsqJbgRW/qd4UurMoXjrVhbwd/x+EgZuI1YPAgEGvSimGKXlovkKROIUA9HCXWwLf8qLG+tefj0SQbmzuOgVKsVIrxSaYNnYg03Jg/VjmuesDEEwlD0+TexrP38T6A1xPp8BXfhQabBsWipL9nyCjgYITlO8irKwdlCGOMFW+IajBWCIw6C0NQO0FS9mT+PupTV0icV+/DaldSXHE6MQAdV0VOv2wsZcqhh3f4dpdggpB5ArU5HT5HSug7f99SqDcapuAgT3dyKTUo3w39gzPCNNnypsq1jIjIvGkG+EAD+syWEsc9AoCjqlEUyRxyclziAR15V2LsnxiMDqS4LRa0zq/1oUctBpdMNe48+TepqUJGDMgAmyH4Vjdlr6RlMlnIzhyQWHNSftAu2yh0IkpLBP6sPlBj/okC5BNbZdDytprDo1n9kMdjAIDQO/8cRCrhi3FsF9zlKnPHGzGP/6R8QhMdZLWD6k4H+b2gf66PJFwdRSiNehOkghWUE1ZQS6o83AosJcX89P9v/Zm6oLhuf5OU4O3Cb2zJcgVVYN7Z1arH3LZLHqn4rcjWkm1cQdMVSTMfSsDCIQSfGfxJDmd78X1UZhT1+X+Er8JdEPGw2xWO+zt4wgfebJw8p2DRx1Vag+/oQlo="
  skip_cleanup: true
  on:
    repo: getcarina/carina
    branch: secure-deploy-with-pull-requests
