language: go
go:
- 1.7
git:
  depth: 9999999
install:
- make get-deps
script:
- make test
- make cross-build
deploy:
- provider: script
  script:
    secure: "4rx0Jo28LbZiqfoSCDCm++0cq3FHNlylVtsS6RixbHPNDPC1Zi+xebP1zteHMvYuqe0hEjE3J3TaTSS4f4d0CqRHEb/7Xbzp3FbphnHHJ4cA9fecaUoD5MvXlTQgqNY2kzTWCdtCgtr22ztOmELFMB/C6rdKeDLQibVuhqgEsoD5F/Gshy8c9Bl4XllGrClAetQyqBZkZLJdU8K4AhoaOCppRQYQktvh+hbOeaL6oBiwFdIktbr9mafvM8zAMMOWINoWdIqppOFC2ou3J1S6/A7754ZUK2NbDBvUM/BVARdCu70FJeuGOEblCJeKQdWHdJ6SiR1F7xXRtmfEitkOXDEameU2M6/Ua98Ew3naS6mp40FCpeAQHiJJuL5tytnqE0Zdz+GmKh6cOcA+5hYEyuFRlcbebKzj0qnSqUG60sIW1B3GltmN7BwtkaEkuMgVdxQA19TyjvTxY3RgxDZrr01rq5F9EBx8F/rNF5kkSW0VWD5si7OTvzZCMTbeEIFh2m40BEC5v8l9oaq9DRe1ZuTEicsWZI4LKttGGKhnr7Pmlxsx1ra7Rc0be4rC6trVAl42dKqiCMFxpzLf2JH9bFPAwQS4KIq1hFkitIlV8MxGEqBFCK4dNGfxTtQ0VeOEa0/lnkmMRkOFvVhWl62JdlDYVH0qJQQP0Q3L3R6TAo0="
  skip_cleanup: true
  on:
    repo: getcarina/carina
    branch: secure-deploy-with-pull-requests
